In [4]:
pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\dines\anaconda3\lib\site-packages (2.0.43)
Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: greenlet>=1 in c:\users\dines\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\dines\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [3]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine(
    "mysql+pymysql://root:password@localhost:3306/retails_sales"
)

In [5]:
#├── Q1. Top-selling Product by Month
query = """
with monthly_saled as (
	select year(o.order_date) as year, month(o.order_date) as month, p.sku, p.category, sum(od.quantity) as total_quantity_sold 
    from orders o join orderdetails od on o.order_id = od.order_id
    join products p on p.product_id = od.product_id
    group by year(o.order_date), month(o.order_date),p.sku,p.category
),

ranked_products as (
select year, month, sku, category, total_quantity_sold, rank() over(partition by year, month order by total_quantity_sold desc)
as sales_rank from monthly_saled
)
select year, month, sku, category, total_quantity_sold from ranked_products where sales_rank = 1 order by year, month;


"""

df = pd.read_sql(query, engine)

df

   year  month              sku       category  total_quantity_sold
0  2022      3   JNE3405-KR-XXL          kurta                  3.0
1  2022      3  SET073-KR-SHA-M            Set                  3.0
2  2022      4     JNE3405-KR-L          kurta                380.0
3  2022      5     JNE3797-KR-S  Western Dress                240.0
4  2022      6     JNE3797-KR-L  Western Dress                340.0

In [6]:
#├── Q2. Sales by Region
query = """
select 
c.region, count(o.order_id) as total_orders, 
round(sum(od.amount), 2) as total_amount 
from customers c join orders o on c.customer_id = o.customer_id 
join orderdetails od on o.order_id = od.order_id
 group by c.region;

"""

df = pd.read_sql(query, engine)

df

      region  total_orders  total_amount
0       West         31393   18905940.54
1      South         52764   31317911.58
2      North         30155   19247929.38
3  Northeast          2747    1729807.78
4       East         11876    7369783.02
5      Other            34      18671.00

In [8]:
#└── Q3. Customers Spending > ₹100,000

query = """
select 
c.customer_id, c.city, c.state, c.region, ( select sum(od.amount) 
from orders o join orderdetails od on od.order_id = o.order_id 
where c.customer_id = o.customer_id) as total_spend
from customers c where ( select sum(od.amount) 
from orders o join orderdetails od on o.order_id = od.order_id 
where c.customer_id = o.customer_id) > 100000
order by total_spend desc;

"""

df = pd.read_sql(query, engine)

df

    customer_id           city          state     region  total_spend
0           181          NOIDA  UTTAR PRADESH      North    622778.37
1           187       GURUGRAM        HARYANA      North    372628.66
2           240      BENGALURU      KARNATAKA      South    356160.19
3            27      BENGALURU      KARNATAKA      South    333519.44
4            52      BENGALURU      KARNATAKA      South    314110.66
..          ...            ...            ...        ...          ...
81          204        UDAIPUR      RAJASTHAN      North    103871.56
82          418          THANE    MAHARASHTRA       West    103603.34
83           50        dimapur       NAGALAND  Northeast    103446.52
84            2      BENGALURU      KARNATAKA      South    102713.57
85         1662  GREATER NOIDA  UTTAR PRADESH      North    101821.72

[86 rows x 5 columns]